apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    svc: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.deployment.name }}
