version: "3"

services:

  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1

  broker:
    container_name: broker
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-vm
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE : "true"

  # kafka_manager:
  #   image: hlebalbau/kafka-manager:stable
  #   container_name: kakfa-manager
  #   restart: always
  #   ports:
  #     - 9000:9000
  #   networks:
  #     - default
  #   environment:
  #     ZK_HOSTS: "zookeeper:2181"
  #     APPLICATION_SECRET: "random-secret"
  #     KAFKA_MANAGER_AUTH_ENABLED: "true"
  #     KAFKA_MANAGER_USERNAME: admin
  #     KAFKA_MANAGER_PASSWORD: smellycat
  #   command: -Dpidfile.path=/dev/null
  